### ISSUE TITLE
Assertion error if requests are sent right after each other

### ISSUE THREAD

**Issue by tobiasWenger** [pouchdb-community/ember-pouch#188]
I have a problem with deleting a record just after saving it (Assertion Failed: Cannot call writableTag after the object is destroyed).

Unfortunately I could not create an Ember Twiddle because the ember-pouch addon could not be loaded. Instead I created a GitHub repo (https://github.com/tobiasWenger/pouchdb-error)

Post model:
```
comments: hasMany('comment', { async: false, dontsave: true }),
messages: hasMany('message', { async: false, dontsave: true })
```

Post controller:
```
import Ember from 'ember';

const {
  Controller,
  get,
  computed: { union },
  RSVP: { Promise }
} = Ember;

export default Controller.extend({
  commentsAndMessages: union('model.comments', 'model.messages'),

  actions: {
    addStuff() {
      this._createAndSave().then(() => {
        this._deleteAll();
      });
    },

    addStuffWithDelay() {
      this._createAndSave().then(() => {
        setTimeout(() => {
          this._deleteAll();
        }, 3000);
      });
    }
  },

  _deleteAll() {
    get(this, 'commentsAndMessages').forEach((commentOrMessage) => {
      commentOrMessage.destroyRecord();
    });
  },

  _createAndSave() {
    const store = get(this, 'store');
    const post = get(this, 'model');

    const comment = store.createRecord('comment', {
      post: post
    });

    const message = store.createRecord('message', {
      post: post
    });

    return Promise.all([
      comment.save(),
      message.save()
    ]);
  }
});
```

The two functions 'addStuff' and 'addStuffWithDelay' are doing basically the same thing. The only difference is the added timeout in 'addStuffWithDelay'.

I hope someone can point me in the right direction to solve this error.

**Comment by jlami** [comment]
Have you tried ember-data ~2.13
There are some problems with 2.14

I'll see if I can repro with your repository.

**Comment by tobiasWenger** [comment]
Thanks for your fast response. I just tried ember data 2.13.2 and the error is still there.

**Comment by jlami** [comment]
I also seem to get the error "Attempted to handle event `pushedData` on <comment:....> while in state root.deleted.inFlight" if I mark the models as async. Maybe that one will give more results while searching, as most of Ember data is expected to work with async=true.

It looks like Ember Data is doing a findRecord or something else that pushes data to the store when it is not supposed to. Might be a race condition, but I would expect the promises to guide this in the right direction, since there is no real remote server in this example.

Would be interesting to see this same test with another adapter.

**Comment by tobiasWenger** [comment]
I'm relieved that you can reproduce the error.

In my real world app I have of course a remote couchdb but I stripped it away for this example. Sometimes I also get other errors like the one you described. It was also my assumption that there is somewhere a race condition.

In my app I think I need async=false to have all data immediately otherwise I end up with a lot more promise objects and I thought with all data locally available it should be fast enough.

I will test this scenario with other adapters and let you know.

**Comment by jlami** [comment]
I have tried it with a slightly modified version of ember-data-in-memory-adapter which does not show these errors.
So I do think that maybe somewhere we have a promise that is not handled correctly.

**Comment by tobiasWenger** [comment]
And I tried it with ember-local-storage with which the error also does not show.

**Comment by jlami** [comment]
Ok, thank you.
This will require some more investigation then.

**Comment by jlami** [comment]
I think this is related to the way we handle the incoming changes from the pouch database. Those trigger reloads, which seem to be starting just after the save, before your delete. But the results might come after your delete. And we probably don't handle detection of existing records when receiving data from the database at that point.

I don't know if we can fix this, or if this is an Ember Data problem.

We could hack around this by recording that the changes don't need to trigger a reload, since the data is already in the local database. But I think this will only shift the problem to a less easily reproducable scenario which involves remote databases. Since those will also trigger our changes listener, which might lead to similar timing problems.

In the end the record state should be taken into account when new data is given to the store, whether that is on our end or on Ember Datas end.

**Comment by jlami** [comment]
You could try the changes-same-revision-hack branch to see if that helps at all. But like I said, I will look further into this.

**Comment by tobiasWenger** [comment]
Thank you very much. In my minimal example it seems to work but in my real app there is still one error:
```
Uncaught (in promise) TypeError: Cannot read property '<property_name>' of undefined
    at getKeyFromDoc (pouchdb.find.js:2412)
    at filterInclusiveStart (pouchdb.find.js:2427)
    at pouchdb.find.js:1658
    at <anonymous>
```
Does this help you or should I try to update the minimal example until this error also occurs? I have to admit that my app has a lot of nested hasMany/belongsTo.

**Comment by jlami** [comment]
Without knowing more I'm afraid I can't say much about that latest error.
If you could find another test case that reproduces this, that would always help.

Do you get this error when you only work with a local database?

You might have to work more with model.get('isDeleted') and/or isLoading/isReloading to filter out items that are not valid. But that should probably be done by helpers already.

**Comment by tobiasWenger** [comment]
I had a lot of filterBy('isDeleted', false) in my computed properties but at least at this time it did not remove the errors.

I will try to create a minimal project tomorrow. I did not use other flags but I will try to do it also tomorrow. The idea with a local database is a good hint. I'll let you know about the progress.

Thanks again for your work.

**Comment by jlami** [comment]
You might also want to try different ember-data versions again, since there might be other bugs that popup now that our bug is somewhat under control. Though the exception location might indicate that we do something wrong when calling pouchdb find. 

Some more information on the location of the exception could help too. Maybe use async stacktraces in Chrome to see more of the backtrace?

**Comment by broerse** [comment]
@tobiasWenger It seems ember-data 2.12.2 is the most stable version for now.

**Comment by tobiasWenger** [comment]
I tested my real app with ember-data 2.12.2 and 2.13.* but with both versions the error is still there.

I tried today to create a minimal project but during 3 hours I could not reproduce the error. I will have to make the sample project bigger but I will be on vacation for the next days and will respond as soon as possible. If I'm lucky I can do it in the next 2 hours.

**Comment by jlami** [comment]
Ok, good luck then. Never a nice thing to go on vacation with such a problem on the back of your mind ;)

**Comment by tobiasWenger** [comment]
Thanks. Good thing is that the app is still in development. No angry customers yet..

**Comment by broerse** [comment]
@tobiasWenger I am responding while I am on vacation. Perhaps we should let @jlami do the hard work while we party ;-)

**Comment by jlami** [comment]
Hope you had a good vacation and can get over those frustrations swiftly ;)

`unloadedDocumentChanged` can indeed introduce a bit of complexity. It is still used in a local only setup, as you can have multiple windows open with the app, and those will then be synced. If you can live without that feature I think there is not much else that I can think of that would stop working without `unloadedDocumentChanged`.

It would be good to know which change triggered the error, but I know debugging this can be very frustrating. Maybe some ember-data fixes will smooth things out in the future as well. But all this does indicate that we might want to look into how we push data into the store as well.
