### ISSUE TITLE
emberpouch/emberPouch case distinction in config

### ISSUE THREAD

**Issue by GregoryAveryWeir** [pouchdb-community/ember-pouch#212]
In the config, DB info must be under the key `emberPouch`, while items like `dontsavehasmany` must be under `emberpouch`. It took me a long time to figure out what was wrong; I think these should be the same key.

Unfortunately, this is likely to be a breaking change for folks who have config files that work with the existing system. I don't know the right remedy for that.

**Comment by broerse** [comment]
@GregoryAveryWeir Thanks for reporting this. We will fix this. We will break it in the next week because we like the `dontsavehasmany` to be the default and will rename to `savehasmany`. We like to do this just before releasing v5.0.0

@jlami My suggestion is to store the new `savehasmany` flag under `emberPouch` but should it be called `saveHasMany` or `savehasMany` in the same style?

**Comment by jlami** [comment]
Maybe it is a good idea to make it `ember-pouch`. I see more and more addons just use their plain name for config. Though I find it a bit annoying to have to use `['ember-pouch']` as a hash key because of the dash.

One other thing about the configuration is that I'm not sure that the adapter should actually use the ember-pouch (or emberPouch) entry. Since this is a application specific thing. The pouch-adapter generator creates a file for you inline with the blueprint, but that becomes part of your own app. The plugin actually doesn't come into play here after that. The remote database name and local database name are totally up to you. It's not even necessary to just have these databases. In case of a scenario where you have multiple databases you might want different config values.

But I can see people expecting these values to be under the same key, so let's work this out.

For the `savehasmany` I'm not really sure. But I was also playing with the idea of having a `persist` option for relationships. That way we can use the same config key if we want to be able to specify this option for belongsTo relationships too.
So maybe a `persistHasMany` for the default value and `persist` for the relationship options? We could do the same with a `save` key for the relationships, but that name seems more dangerous, we don't want to shadow a future ember-data option. Though that one might be more logical.

**Comment by broerse** [comment]
@GregoryAveryWeir Fixed in the just released v5.0.0
