### ISSUE TITLE
How to avoid `onChange` from running after store has been destroyed?

### ISSUE THREAD

**Issue by jacobq** [pouchdb-community/ember-pouch#251]
When testing, I find that often the following code causes a deprecation warning to appear 

https://github.com/pouchdb-community/ember-pouch/blob/fe5fc20a8e6f10a9f1af68f9bdf8b7517089695c/addon/adapters/pouch.js#L104

> DEPRECATION: Attempted to call `store._modelFactoryFor()`, but the store instance has already been destroyed. [deprecation id: ember-data:method-calls-on-destroyed-store]

I believe this is because my tests finish before pouch has settled/finished, and I'd like to know if this addon provides any tools to help deal with this? I see that some kind of waiter was added in https://github.com/pouchdb-community/ember-pouch/pull/200 but it looks like it never landed in `master`.

**Comment by broerse** [comment]
@jacobq like to let you know that I like what you are doing and will invest time to update ember-pouch from next week on.

**Comment by jlami** [comment]
That is a bit odd, we do remove our change listener when the adapter gets a `willDestroy` signal. So I would expect it not to happen.
But looking at the ember-data store code I see that they don't really destroy adapters, so maybe our adapter outlives the store just long enough to catch some pouch changes. Although I would expect ember to destroy all the items inside its container at the same time.

I'm in the middle of rewriting some of the init code to make it wait for the creation of the views on setup instead of on test tear down. This might remove some of these errors too if it is a timing thing on our side.

But to really fix it we might have to check store.isDestroying/isDestroyed

**Comment by jacobq** [comment]
I can't remember now since I haven't been looking at this lately, but this may have been due to improper synchronization in my tests (e.g. had an async `instance-initializer` that would be doing some work with the `store` without the test framework knowing that it needed to wait, etc.).

**Comment by jlami** [comment]
Ok, let's close this issue for now then. Feel free to reopen if you run into this again.
